version: "3.9"

services:
  api:
    build: .
    image: attendance-api
    container_name: attendance-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db_service
    restart: unless-stopped

  db_service:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_attend_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
